  
  export const initialItems = [
    // Sweets
    { id: self.crypto.randomUUID(), emoji: '🍩', name: 'doughnut', sugarPerPiece: 11, pieces: 1, isInitial: true },
    { id: self.crypto.randomUUID(), emoji: '🍪', name: 'cookie', sugarPerPiece: 7, pieces: 1, isInitial: true },
    { id: self.crypto.randomUUID(), emoji: '🍫', name: 'chocolate bar', sugarPerPiece: 24, pieces: 1, isInitial: true },
    { id: self.crypto.randomUUID(), emoji: '🍬', name: 'candy', sugarPerPiece: 6, pieces: 1, isInitial: true },
    { id: self.crypto.randomUUID(), emoji: '🍭', name: 'lollipop', sugarPerPiece: 10, pieces: 1, isInitial: true },
    { id: self.crypto.randomUUID(), emoji: '🍮', name: 'custard', sugarPerPiece: 21, pieces: 1, isInitial: true },
    { id: self.crypto.randomUUID(), emoji: '🍰', name: 'shortcake', sugarPerPiece: 21, pieces: 1, isInitial: true },
    { id: self.crypto.randomUUID(), emoji: '🎂', name: 'cake', sugarPerPiece: 30, pieces: 1, isInitial: true },
    { id: self.crypto.randomUUID(), emoji: '🧁', name: 'cupcake', sugarPerPiece: 21, pieces: 1, isInitial: true },
    { id: self.crypto.randomUUID(), emoji: '🥧', name: 'pie', sugarPerPiece: 20, pieces: 1, isInitial: true },
    { id: self.crypto.randomUUID(), emoji: '🍨', name: 'ice cream', sugarPerPiece: 28, pieces: 1, isInitial: true },
    { id: self.crypto.randomUUID(), emoji: '🍧', name: 'shaved ice', sugarPerPiece: 27, pieces: 1, isInitial: true },
    { id: self.crypto.randomUUID(), emoji: '🍦', name: 'soft ice cream', sugarPerPiece: 28, pieces: 1, isInitial: true },
    { id: self.crypto.randomUUID(), emoji: '🥠', name: 'fortune cookie', sugarPerPiece: 3, pieces: 1, isInitial: true },
    { id: self.crypto.randomUUID(), emoji: '🍡', name: 'dango', sugarPerPiece: 8, pieces: 1, isInitial: true },
    // Drinks
    { id: self.crypto.randomUUID(), emoji: '🍹', name: 'cocktail', sugarPerPiece: 20, pieces: 1, isInitial: true },
    { id: self.crypto.randomUUID(), emoji: '🍸', name: 'alcohol', sugarPerPiece: 1, pieces: 1, isInitial: true },
    { id: self.crypto.randomUUID(), emoji: '🥃', name: 'alcohol', sugarPerPiece: 1, pieces: 1, isInitial: true },
    { id: self.crypto.randomUUID(), emoji: '🥤', name: 'soft drink', sugarPerPiece: 39, pieces: 1, isInitial: true },
    { id: self.crypto.randomUUID(), emoji: '🧃', name: 'juice', sugarPerPiece: 20, pieces: 1, isInitial: true },
    { id: self.crypto.randomUUID(), emoji: '🍷', name: 'wine', sugarPerPiece: 1, pieces: 1, isInitial: true },
    { id: self.crypto.randomUUID(), emoji: '🍾', name: 'champagne', sugarPerPiece: 1, pieces: 1, isInitial: true },
    { id: self.crypto.randomUUID(), emoji: '🥛', name: 'yogurt', sugarPerPiece: 10, pieces: 1, isInitial: true },
    { id: self.crypto.randomUUID(), emoji: '🧋', name: 'bubble tea', sugarPerPiece: 38, pieces: 1, isInitial: true },
    { id: self.crypto.randomUUID(), emoji: '☕', name: 'coffee', sugarPerPiece: 5, pieces: 1, isInitial: true },
    { id: self.crypto.randomUUID(), emoji: '☕', name: 'tea', sugarPerPiece: 5, pieces: 1, isInitial: true },
    // Foods with added sugar
    { id: self.crypto.randomUUID(), emoji: '🍔', name: 'burger', sugarPerPiece: 5, pieces: 1, isInitial: true },
    { id: self.crypto.randomUUID(), emoji: '🍕', name: 'pizza', sugarPerPiece: 4, pieces: 1, isInitial: true },
    { id: self.crypto.randomUUID(), emoji: '🌭', name: 'hotdog', sugarPerPiece: 2, pieces: 1, isInitial: true },
    { id: self.crypto.randomUUID(), emoji: '🥪', name: 'sandwich', sugarPerPiece: 3, pieces: 1, isInitial: true },
    { id: self.crypto.randomUUID(), emoji: '🍝', name: 'spaghetti', sugarPerPiece: 1, pieces: 1, isInitial: true },
    { id: self.crypto.randomUUID(), emoji: '🍿', name: 'popcorn', sugarPerPiece: 1, pieces: 1, isInitial: true },
    { id: self.crypto.randomUUID(), emoji: '🥐', name: 'croissant', sugarPerPiece: 5, pieces: 1, isInitial: true },
    { id: self.crypto.randomUUID(), emoji: '🥞', name: 'pancake', sugarPerPiece: 10, pieces: 1, isInitial: true },
    { id: self.crypto.randomUUID(), emoji: '🧇', name: 'waffle', sugarPerPiece: 10, pieces: 1, isInitial: true },
    { id: self.crypto.randomUUID(), emoji: '🍶', name: 'sauce', sugarPerPiece: 10, pieces: 1, isInitial: true },
    { id: self.crypto.randomUUID(), emoji: '🥜', name: 'granola', sugarPerPiece: 6, pieces: 1, isInitial: true },
    { id: self.crypto.randomUUID(), emoji: '🥣', name: 'cereal', sugarPerPiece: 10, pieces: 1, isInitial: true },
    { id: self.crypto.randomUUID(), emoji: '🥫', name: 'ketchup', sugarPerPiece: 10, pieces: 1, isInitial: true },
    { id: self.crypto.randomUUID(), emoji: '🍯', name: 'honey', sugarPerPiece: 17, pieces: 1, isInitial: true },
    // Other
    { id: self.crypto.randomUUID(), emoji: '🥄', name: 'other', sugarPerPiece: 5, pieces: 1, isInitial: true },
    { id: self.crypto.randomUUID(), emoji: '🧊', name: 'other', sugarPerPiece: 5, pieces: 1, isInitial: true },
  ]
  
  